// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.options.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.models.extensions.AutomaticRepliesSetting;
import com.microsoft.graph.models.extensions.LocaleInfo;
import com.microsoft.graph.models.generated.DelegateMeetingMessageDeliveryOptions;
import com.microsoft.graph.models.extensions.WorkingHours;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Mailbox Settings.
 */
public class MailboxSettings implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Automatic Replies Setting.
     * 
     */
    @SerializedName("automaticRepliesSetting")
    @Expose
    public AutomaticRepliesSetting automaticRepliesSetting;

    /**
     * The Archive Folder.
     * 
     */
    @SerializedName("archiveFolder")
    @Expose
    public String archiveFolder;

    /**
     * The Time Zone.
     * 
     */
    @SerializedName("timeZone")
    @Expose
    public String timeZone;

    /**
     * The Language.
     * 
     */
    @SerializedName("language")
    @Expose
    public LocaleInfo language;

    /**
     * The Delegate Meeting Message Delivery Options.
     * 
     */
    @SerializedName("delegateMeetingMessageDeliveryOptions")
    @Expose
    public DelegateMeetingMessageDeliveryOptions delegateMeetingMessageDeliveryOptions;

    /**
     * The Working Hours.
     * 
     */
    @SerializedName("workingHours")
    @Expose
    public WorkingHours workingHours;

    /**
     * The Date Format.
     * 
     */
    @SerializedName("dateFormat")
    @Expose
    public String dateFormat;

    /**
     * The Time Format.
     * 
     */
    @SerializedName("timeFormat")
    @Expose
    public String timeFormat;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
