// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.options.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.models.generated.MessageActionFlag;
import com.microsoft.graph.models.generated.Importance;
import com.microsoft.graph.models.generated.Sensitivity;
import com.microsoft.graph.models.extensions.Recipient;
import com.microsoft.graph.models.extensions.SizeRange;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Message Rule Predicates.
 */
public class MessageRulePredicates implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Categories.
     * 
     */
    @SerializedName("categories")
    @Expose
    public java.util.List<String> categories;

    /**
     * The Subject Contains.
     * 
     */
    @SerializedName("subjectContains")
    @Expose
    public java.util.List<String> subjectContains;

    /**
     * The Body Contains.
     * 
     */
    @SerializedName("bodyContains")
    @Expose
    public java.util.List<String> bodyContains;

    /**
     * The Body Or Subject Contains.
     * 
     */
    @SerializedName("bodyOrSubjectContains")
    @Expose
    public java.util.List<String> bodyOrSubjectContains;

    /**
     * The Sender Contains.
     * 
     */
    @SerializedName("senderContains")
    @Expose
    public java.util.List<String> senderContains;

    /**
     * The Recipient Contains.
     * 
     */
    @SerializedName("recipientContains")
    @Expose
    public java.util.List<String> recipientContains;

    /**
     * The Header Contains.
     * 
     */
    @SerializedName("headerContains")
    @Expose
    public java.util.List<String> headerContains;

    /**
     * The Message Action Flag.
     * 
     */
    @SerializedName("messageActionFlag")
    @Expose
    public MessageActionFlag messageActionFlag;

    /**
     * The Importance.
     * 
     */
    @SerializedName("importance")
    @Expose
    public Importance importance;

    /**
     * The Sensitivity.
     * 
     */
    @SerializedName("sensitivity")
    @Expose
    public Sensitivity sensitivity;

    /**
     * The From Addresses.
     * 
     */
    @SerializedName("fromAddresses")
    @Expose
    public java.util.List<Recipient> fromAddresses;

    /**
     * The Sent To Addresses.
     * 
     */
    @SerializedName("sentToAddresses")
    @Expose
    public java.util.List<Recipient> sentToAddresses;

    /**
     * The Sent To Me.
     * 
     */
    @SerializedName("sentToMe")
    @Expose
    public Boolean sentToMe;

    /**
     * The Sent Only To Me.
     * 
     */
    @SerializedName("sentOnlyToMe")
    @Expose
    public Boolean sentOnlyToMe;

    /**
     * The Sent Cc Me.
     * 
     */
    @SerializedName("sentCcMe")
    @Expose
    public Boolean sentCcMe;

    /**
     * The Sent To Or Cc Me.
     * 
     */
    @SerializedName("sentToOrCcMe")
    @Expose
    public Boolean sentToOrCcMe;

    /**
     * The Not Sent To Me.
     * 
     */
    @SerializedName("notSentToMe")
    @Expose
    public Boolean notSentToMe;

    /**
     * The Has Attachments.
     * 
     */
    @SerializedName("hasAttachments")
    @Expose
    public Boolean hasAttachments;

    /**
     * The Is Approval Request.
     * 
     */
    @SerializedName("isApprovalRequest")
    @Expose
    public Boolean isApprovalRequest;

    /**
     * The Is Automatic Forward.
     * 
     */
    @SerializedName("isAutomaticForward")
    @Expose
    public Boolean isAutomaticForward;

    /**
     * The Is Automatic Reply.
     * 
     */
    @SerializedName("isAutomaticReply")
    @Expose
    public Boolean isAutomaticReply;

    /**
     * The Is Encrypted.
     * 
     */
    @SerializedName("isEncrypted")
    @Expose
    public Boolean isEncrypted;

    /**
     * The Is Meeting Request.
     * 
     */
    @SerializedName("isMeetingRequest")
    @Expose
    public Boolean isMeetingRequest;

    /**
     * The Is Meeting Response.
     * 
     */
    @SerializedName("isMeetingResponse")
    @Expose
    public Boolean isMeetingResponse;

    /**
     * The Is Non Delivery Report.
     * 
     */
    @SerializedName("isNonDeliveryReport")
    @Expose
    public Boolean isNonDeliveryReport;

    /**
     * The Is Permission Controlled.
     * 
     */
    @SerializedName("isPermissionControlled")
    @Expose
    public Boolean isPermissionControlled;

    /**
     * The Is Read Receipt.
     * 
     */
    @SerializedName("isReadReceipt")
    @Expose
    public Boolean isReadReceipt;

    /**
     * The Is Signed.
     * 
     */
    @SerializedName("isSigned")
    @Expose
    public Boolean isSigned;

    /**
     * The Is Voicemail.
     * 
     */
    @SerializedName("isVoicemail")
    @Expose
    public Boolean isVoicemail;

    /**
     * The Within Size Range.
     * 
     */
    @SerializedName("withinSizeRange")
    @Expose
    public SizeRange withinSizeRange;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
