// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.models.generated.Importance;
import com.microsoft.graph.models.extensions.Recipient;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Message Rule Actions.
 */
public class MessageRuleActions implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Move To Folder.
     * 
     */
    @SerializedName("moveToFolder")
    @Expose
    public String moveToFolder;

    /**
     * The Copy To Folder.
     * 
     */
    @SerializedName("copyToFolder")
    @Expose
    public String copyToFolder;

    /**
     * The Delete.
     * 
     */
    @SerializedName("delete")
    @Expose
    public Boolean delete;

    /**
     * The Permanent Delete.
     * 
     */
    @SerializedName("permanentDelete")
    @Expose
    public Boolean permanentDelete;

    /**
     * The Mark As Read.
     * 
     */
    @SerializedName("markAsRead")
    @Expose
    public Boolean markAsRead;

    /**
     * The Mark Importance.
     * 
     */
    @SerializedName("markImportance")
    @Expose
    public Importance markImportance;

    /**
     * The Forward To.
     * 
     */
    @SerializedName("forwardTo")
    @Expose
    public java.util.List<Recipient> forwardTo;

    /**
     * The Forward As Attachment To.
     * 
     */
    @SerializedName("forwardAsAttachmentTo")
    @Expose
    public java.util.List<Recipient> forwardAsAttachmentTo;

    /**
     * The Redirect To.
     * 
     */
    @SerializedName("redirectTo")
    @Expose
    public java.util.List<Recipient> redirectTo;

    /**
     * The Assign Categories.
     * 
     */
    @SerializedName("assignCategories")
    @Expose
    public java.util.List<String> assignCategories;

    /**
     * The Stop Processing Rules.
     * 
     */
    @SerializedName("stopProcessingRules")
    @Expose
    public Boolean stopProcessingRules;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
