// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.models.extensions.IdentitySet;
import com.microsoft.graph.models.extensions.ItemReference;
import com.microsoft.graph.models.extensions.SharingInvitation;
import com.microsoft.graph.models.extensions.SharingLink;
import com.microsoft.graph.models.extensions.Entity;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Permission.
 */
public class Permission extends Entity implements IJsonBackedObject {


    /**
     * The Expiration Date Time.
     * 
     */
    @SerializedName("expirationDateTime")
    @Expose
    public java.util.Calendar expirationDateTime;

    /**
     * The Granted To.
     * 
     */
    @SerializedName("grantedTo")
    @Expose
    public IdentitySet grantedTo;

    /**
     * The Granted To Identities.
     * 
     */
    @SerializedName("grantedToIdentities")
    @Expose
    public java.util.List<IdentitySet> grantedToIdentities;

    /**
     * The Has Password.
     * 
     */
    @SerializedName("hasPassword")
    @Expose
    public Boolean hasPassword;

    /**
     * The Inherited From.
     * 
     */
    @SerializedName("inheritedFrom")
    @Expose
    public ItemReference inheritedFrom;

    /**
     * The Invitation.
     * 
     */
    @SerializedName("invitation")
    @Expose
    public SharingInvitation invitation;

    /**
     * The Link.
     * 
     */
    @SerializedName("link")
    @Expose
    public SharingLink link;

    /**
     * The Roles.
     * 
     */
    @SerializedName("roles")
    @Expose
    public java.util.List<String> roles;

    /**
     * The Share Id.
     * 
     */
    @SerializedName("shareId")
    @Expose
    public String shareId;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
