// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Teleconference Device Media Quality.
 */
public class TeleconferenceDeviceMediaQuality implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Channel Index.
     * 
     */
    @SerializedName("channelIndex")
    @Expose
    public Integer channelIndex;

    /**
     * The Media Duration.
     * 
     */
    @SerializedName("mediaDuration")
    @Expose
    public javax.xml.datatype.Duration mediaDuration;

    /**
     * The Network Link Speed In Bytes.
     * 
     */
    @SerializedName("networkLinkSpeedInBytes")
    @Expose
    public Long networkLinkSpeedInBytes;

    /**
     * The Local IPAddress.
     * 
     */
    @SerializedName("localIPAddress")
    @Expose
    public String localIPAddress;

    /**
     * The Local Port.
     * 
     */
    @SerializedName("localPort")
    @Expose
    public Integer localPort;

    /**
     * The Remote IPAddress.
     * 
     */
    @SerializedName("remoteIPAddress")
    @Expose
    public String remoteIPAddress;

    /**
     * The Remote Port.
     * 
     */
    @SerializedName("remotePort")
    @Expose
    public Integer remotePort;

    /**
     * The Inbound Packets.
     * 
     */
    @SerializedName("inboundPackets")
    @Expose
    public Long inboundPackets;

    /**
     * The Outbound Packets.
     * 
     */
    @SerializedName("outboundPackets")
    @Expose
    public Long outboundPackets;

    /**
     * The Average Inbound Packet Loss Rate In Percentage.
     * 
     */
    @SerializedName("averageInboundPacketLossRateInPercentage")
    @Expose
    public Double averageInboundPacketLossRateInPercentage;

    /**
     * The Average Outbound Packet Loss Rate In Percentage.
     * 
     */
    @SerializedName("averageOutboundPacketLossRateInPercentage")
    @Expose
    public Double averageOutboundPacketLossRateInPercentage;

    /**
     * The Maximum Inbound Packet Loss Rate In Percentage.
     * 
     */
    @SerializedName("maximumInboundPacketLossRateInPercentage")
    @Expose
    public Double maximumInboundPacketLossRateInPercentage;

    /**
     * The Maximum Outbound Packet Loss Rate In Percentage.
     * 
     */
    @SerializedName("maximumOutboundPacketLossRateInPercentage")
    @Expose
    public Double maximumOutboundPacketLossRateInPercentage;

    /**
     * The Average Inbound Round Trip Delay.
     * 
     */
    @SerializedName("averageInboundRoundTripDelay")
    @Expose
    public javax.xml.datatype.Duration averageInboundRoundTripDelay;

    /**
     * The Average Outbound Round Trip Delay.
     * 
     */
    @SerializedName("averageOutboundRoundTripDelay")
    @Expose
    public javax.xml.datatype.Duration averageOutboundRoundTripDelay;

    /**
     * The Maximum Inbound Round Trip Delay.
     * 
     */
    @SerializedName("maximumInboundRoundTripDelay")
    @Expose
    public javax.xml.datatype.Duration maximumInboundRoundTripDelay;

    /**
     * The Maximum Outbound Round Trip Delay.
     * 
     */
    @SerializedName("maximumOutboundRoundTripDelay")
    @Expose
    public javax.xml.datatype.Duration maximumOutboundRoundTripDelay;

    /**
     * The Average Inbound Jitter.
     * 
     */
    @SerializedName("averageInboundJitter")
    @Expose
    public javax.xml.datatype.Duration averageInboundJitter;

    /**
     * The Average Outbound Jitter.
     * 
     */
    @SerializedName("averageOutboundJitter")
    @Expose
    public javax.xml.datatype.Duration averageOutboundJitter;

    /**
     * The Maximum Inbound Jitter.
     * 
     */
    @SerializedName("maximumInboundJitter")
    @Expose
    public javax.xml.datatype.Duration maximumInboundJitter;

    /**
     * The Maximum Outbound Jitter.
     * 
     */
    @SerializedName("maximumOutboundJitter")
    @Expose
    public javax.xml.datatype.Duration maximumOutboundJitter;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
