// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.models.extensions.TeleconferenceDeviceMediaQuality;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Teleconference Device Quality.
 */
public class TeleconferenceDeviceQuality implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Call Chain Id.
     * 
     */
    @SerializedName("callChainId")
    @Expose
    public java.util.UUID callChainId;

    /**
     * The Participant Id.
     * 
     */
    @SerializedName("participantId")
    @Expose
    public java.util.UUID participantId;

    /**
     * The Media Leg Id.
     * 
     */
    @SerializedName("mediaLegId")
    @Expose
    public java.util.UUID mediaLegId;

    /**
     * The Device Name.
     * 
     */
    @SerializedName("deviceName")
    @Expose
    public String deviceName;

    /**
     * The Device Description.
     * 
     */
    @SerializedName("deviceDescription")
    @Expose
    public String deviceDescription;

    /**
     * The Cloud Service Name.
     * 
     */
    @SerializedName("cloudServiceName")
    @Expose
    public String cloudServiceName;

    /**
     * The Cloud Service Instance Name.
     * 
     */
    @SerializedName("cloudServiceInstanceName")
    @Expose
    public String cloudServiceInstanceName;

    /**
     * The Cloud Service Deployment Id.
     * 
     */
    @SerializedName("cloudServiceDeploymentId")
    @Expose
    public String cloudServiceDeploymentId;

    /**
     * The Cloud Service Deployment Environment.
     * 
     */
    @SerializedName("cloudServiceDeploymentEnvironment")
    @Expose
    public String cloudServiceDeploymentEnvironment;

    /**
     * The Media Quality List.
     * 
     */
    @SerializedName("mediaQualityList")
    @Expose
    public java.util.List<TeleconferenceDeviceMediaQuality> mediaQualityList;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
