// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.callrecords.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.callrecords.models.generated.MediaStreamDirection;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Media Stream.
 */
public class MediaStream implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Stream Id.
     * 
     */
    @SerializedName("streamId")
    @Expose
    public String streamId;

    /**
     * The Start Date Time.
     * 
     */
    @SerializedName("startDateTime")
    @Expose
    public java.util.Calendar startDateTime;

    /**
     * The End Date Time.
     * 
     */
    @SerializedName("endDateTime")
    @Expose
    public java.util.Calendar endDateTime;

    /**
     * The Stream Direction.
     * 
     */
    @SerializedName("streamDirection")
    @Expose
    public MediaStreamDirection streamDirection;

    /**
     * The Average Audio Degradation.
     * 
     */
    @SerializedName("averageAudioDegradation")
    @Expose
    public float averageAudioDegradation;

    /**
     * The Average Jitter.
     * 
     */
    @SerializedName("averageJitter")
    @Expose
    public javax.xml.datatype.Duration averageJitter;

    /**
     * The Max Jitter.
     * 
     */
    @SerializedName("maxJitter")
    @Expose
    public javax.xml.datatype.Duration maxJitter;

    /**
     * The Average Packet Loss Rate.
     * 
     */
    @SerializedName("averagePacketLossRate")
    @Expose
    public float averagePacketLossRate;

    /**
     * The Max Packet Loss Rate.
     * 
     */
    @SerializedName("maxPacketLossRate")
    @Expose
    public float maxPacketLossRate;

    /**
     * The Average Ratio Of Concealed Samples.
     * 
     */
    @SerializedName("averageRatioOfConcealedSamples")
    @Expose
    public float averageRatioOfConcealedSamples;

    /**
     * The Max Ratio Of Concealed Samples.
     * 
     */
    @SerializedName("maxRatioOfConcealedSamples")
    @Expose
    public float maxRatioOfConcealedSamples;

    /**
     * The Average Round Trip Time.
     * 
     */
    @SerializedName("averageRoundTripTime")
    @Expose
    public javax.xml.datatype.Duration averageRoundTripTime;

    /**
     * The Max Round Trip Time.
     * 
     */
    @SerializedName("maxRoundTripTime")
    @Expose
    public javax.xml.datatype.Duration maxRoundTripTime;

    /**
     * The Packet Utilization.
     * 
     */
    @SerializedName("packetUtilization")
    @Expose
    public Long packetUtilization;

    /**
     * The Average Bandwidth Estimate.
     * 
     */
    @SerializedName("averageBandwidthEstimate")
    @Expose
    public Long averageBandwidthEstimate;

    /**
     * The Was Media Bypassed.
     * 
     */
    @SerializedName("wasMediaBypassed")
    @Expose
    public Boolean wasMediaBypassed;

    /**
     * The Post Forward Error Correction Packet Loss Rate.
     * 
     */
    @SerializedName("postForwardErrorCorrectionPacketLossRate")
    @Expose
    public float postForwardErrorCorrectionPacketLossRate;

    /**
     * The Average Video Frame Loss Percentage.
     * 
     */
    @SerializedName("averageVideoFrameLossPercentage")
    @Expose
    public float averageVideoFrameLossPercentage;

    /**
     * The Average Received Frame Rate.
     * 
     */
    @SerializedName("averageReceivedFrameRate")
    @Expose
    public float averageReceivedFrameRate;

    /**
     * The Low Frame Rate Ratio.
     * 
     */
    @SerializedName("lowFrameRateRatio")
    @Expose
    public float lowFrameRateRatio;

    /**
     * The Average Video Packet Loss Rate.
     * 
     */
    @SerializedName("averageVideoPacketLossRate")
    @Expose
    public float averageVideoPacketLossRate;

    /**
     * The Average Video Frame Rate.
     * 
     */
    @SerializedName("averageVideoFrameRate")
    @Expose
    public float averageVideoFrameRate;

    /**
     * The Low Video Processing Capability Ratio.
     * 
     */
    @SerializedName("lowVideoProcessingCapabilityRatio")
    @Expose
    public float lowVideoProcessingCapabilityRatio;

    /**
     * The Average Audio Network Jitter.
     * 
     */
    @SerializedName("averageAudioNetworkJitter")
    @Expose
    public javax.xml.datatype.Duration averageAudioNetworkJitter;

    /**
     * The Max Audio Network Jitter.
     * 
     */
    @SerializedName("maxAudioNetworkJitter")
    @Expose
    public javax.xml.datatype.Duration maxAudioNetworkJitter;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
