// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.callrecords.models.extensions;
import com.microsoft.graph.concurrency.*;
import com.microsoft.graph.core.*;
import com.microsoft.graph.http.*;
import com.microsoft.graph.serializer.*;
import java.util.Arrays;
import java.util.EnumSet;
import com.microsoft.graph.callrecords.models.generated.NetworkConnectionType;
import com.microsoft.graph.callrecords.models.generated.WifiBand;
import com.microsoft.graph.callrecords.models.generated.WifiRadioType;


import com.google.gson.JsonObject;
import com.google.gson.JsonElement;
import com.google.gson.annotations.*;
import java.util.HashMap;
import java.util.Map;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Network Info.
 */
public class NetworkInfo implements IJsonBackedObject {

    @SerializedName("@odata.type")
    @Expose
    public String oDataType;

    private transient AdditionalDataManager additionalDataManager = new AdditionalDataManager(this);

    @Override
    public final AdditionalDataManager additionalDataManager() {
        return additionalDataManager;
    }

    /**
     * The Ip Address.
     * 
     */
    @SerializedName("ipAddress")
    @Expose
    public String ipAddress;

    /**
     * The Subnet.
     * 
     */
    @SerializedName("subnet")
    @Expose
    public String subnet;

    /**
     * The Link Speed.
     * 
     */
    @SerializedName("linkSpeed")
    @Expose
    public Long linkSpeed;

    /**
     * The Connection Type.
     * 
     */
    @SerializedName("connectionType")
    @Expose
    public NetworkConnectionType connectionType;

    /**
     * The Port.
     * 
     */
    @SerializedName("port")
    @Expose
    public Integer port;

    /**
     * The Reflexive IPAddress.
     * 
     */
    @SerializedName("reflexiveIPAddress")
    @Expose
    public String reflexiveIPAddress;

    /**
     * The Relay IPAddress.
     * 
     */
    @SerializedName("relayIPAddress")
    @Expose
    public String relayIPAddress;

    /**
     * The Relay Port.
     * 
     */
    @SerializedName("relayPort")
    @Expose
    public Integer relayPort;

    /**
     * The Mac Address.
     * 
     */
    @SerializedName("macAddress")
    @Expose
    public String macAddress;

    /**
     * The Wifi Microsoft Driver.
     * 
     */
    @SerializedName("wifiMicrosoftDriver")
    @Expose
    public String wifiMicrosoftDriver;

    /**
     * The Wifi Microsoft Driver Version.
     * 
     */
    @SerializedName("wifiMicrosoftDriverVersion")
    @Expose
    public String wifiMicrosoftDriverVersion;

    /**
     * The Wifi Vendor Driver.
     * 
     */
    @SerializedName("wifiVendorDriver")
    @Expose
    public String wifiVendorDriver;

    /**
     * The Wifi Vendor Driver Version.
     * 
     */
    @SerializedName("wifiVendorDriverVersion")
    @Expose
    public String wifiVendorDriverVersion;

    /**
     * The Wifi Channel.
     * 
     */
    @SerializedName("wifiChannel")
    @Expose
    public Integer wifiChannel;

    /**
     * The Wifi Band.
     * 
     */
    @SerializedName("wifiBand")
    @Expose
    public WifiBand wifiBand;

    /**
     * The Basic Service Set Identifier.
     * 
     */
    @SerializedName("basicServiceSetIdentifier")
    @Expose
    public String basicServiceSetIdentifier;

    /**
     * The Wifi Radio Type.
     * 
     */
    @SerializedName("wifiRadioType")
    @Expose
    public WifiRadioType wifiRadioType;

    /**
     * The Wifi Signal Strength.
     * 
     */
    @SerializedName("wifiSignalStrength")
    @Expose
    public Integer wifiSignalStrength;

    /**
     * The Wifi Battery Charge.
     * 
     */
    @SerializedName("wifiBatteryCharge")
    @Expose
    public Integer wifiBatteryCharge;

    /**
     * The Dns Suffix.
     * 
     */
    @SerializedName("dnsSuffix")
    @Expose
    public String dnsSuffix;

    /**
     * The Sent Quality Event Ratio.
     * 
     */
    @SerializedName("sentQualityEventRatio")
    @Expose
    public float sentQualityEventRatio;

    /**
     * The Received Quality Event Ratio.
     * 
     */
    @SerializedName("receivedQualityEventRatio")
    @Expose
    public float receivedQualityEventRatio;

    /**
     * The Delay Event Ratio.
     * 
     */
    @SerializedName("delayEventRatio")
    @Expose
    public float delayEventRatio;

    /**
     * The Bandwidth Low Event Ratio.
     * 
     */
    @SerializedName("bandwidthLowEventRatio")
    @Expose
    public float bandwidthLowEventRatio;


    /**
     * The raw representation of this class
     */
    private JsonObject rawObject;

    /**
     * The serializer
     */
    private ISerializer serializer;

    /**
     * Gets the raw representation of this class
     *
     * @return the raw representation of this class
     */
    public JsonObject getRawObject() {
        return rawObject;
    }

    /**
     * Gets serializer
     *
     * @return the serializer
     */
    protected ISerializer getSerializer() {
        return serializer;
    }

    /**
     * Sets the raw JSON object
     *
     * @param serializer the serializer
     * @param json the JSON object to set this object to
     */
    public void setRawObject(final ISerializer serializer, final JsonObject json) {
        this.serializer = serializer;
        rawObject = json;

    }
}
